import type { Registry } from "./schema";

export const component: Registry = [
    {
        name: "ai-input-01",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ai-input-01.tsx"],
    },
    {
        name: "ai-input-02",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ai-input-02.tsx"],
    },
    {
        name: "ai-input-03",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ai-input-03.tsx"],
    },
    {
        name: "ai-input-04",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ai-input-04.tsx"],
    },
    {
        name: "ai-input-05",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ai-input-05.tsx"],
    },
    {
        name: "ai-input-06",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ai-input-06.tsx"],
    },
    {
        name: "ai-input-07",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ai-input-07.tsx"],
    },
    {
        name: "ai-input-08",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ai-input-08.tsx"],
    },
    {
        name: "ai-input-09",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ai-input-09.tsx"],
    },
    {
        name: "ai-input-10",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ai-input-10.tsx"],
    },
    {
        name: "ai-input-11",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ai-input-11.tsx"],
    },
    {
        name: "ai-input-12",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea", "tooltip"],
        files: ["ai-input-12.tsx"],
    },
    {
        name: "ai-input-13",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ai-input-13.tsx"],
    },
    {
        name: "ai-input-14",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ai-input-14.tsx"],
    },
    {
        name: "ai-input-15",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ai-input-15.tsx"],
    },
    {
        name: "ai-input-16",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ai-input-16.tsx"],
    },
    {
        name: "ai-input-17",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ai-input-17.tsx"],
    },
    {
        name: "ai-input-18",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ai-input-18.tsx"],
    },
    {
        name: "ai-input-19",
        type: "registry:component",
        dependencies: ["lucide-react", "framer-motion"],
        registryDependencies: ["textarea"],
        files: ["ai-input-19.tsx"],
    },
    {
        name: "ai-input-20",
        type: "registry:component",
        dependencies: ["lucide-react", "framer-motion", "cmdk"],
        registryDependencies: ["textarea"],
        files: ["ai-input-20.tsx"],
    },
    {
        name: "btn-01",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["button"],
        files: ["btn-01.tsx"],
    },
    {
        name: "btn-02",
        type: "registry:component",
        registryDependencies: ["button"],
        files: ["btn-02.tsx"],
    },
    {
        name: "btn-03",
        type: "registry:component",
        dependencies: ["lucide-react", "framer-motion"],
        registryDependencies: ["button"],
        files: ["btn-03.tsx"],
    },
    {
        name: "btn-04",
        type: "registry:component",
        dependencies: ["lucide-react", "framer-motion"],
        registryDependencies: ["button"],
        files: ["btn-04.tsx"],
    },
    {
        name: "btn-05",
        type: "registry:component",
        dependencies: ["lucide-react", "framer-motion"],
        registryDependencies: ["button"],
        files: ["btn-05.tsx"],
    },
    {
        name: "btn-06",
        type: "registry:component",
        dependencies: ["lucide-react", "framer-motion"],
        registryDependencies: ["button"],
        files: ["btn-06.tsx"],
    },
    {
        name: "btn-07",
        type: "registry:component",
        dependencies: ["lucide-react", "framer-motion"],
        registryDependencies: ["button"],
        files: ["btn-07.tsx"],
    },
    {
        name: "btn-08",
        type: "registry:component",
        dependencies: ["lucide-react", "framer-motion"],
        registryDependencies: ["button"],
        files: ["btn-08.tsx"],
    },
    {
        name: "btn-09",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["button"],
        files: ["btn-09.tsx"],
    },
    {
        name: "btn-10",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["button"],
        files: ["btn-10.tsx"],
    },
    {
        name: "text-01",
        type: "registry:component",
        dependencies: ["lucide-react"],
        files: ["text-01.tsx"],
    },
    {
        name: "text-02",
        type: "registry:component",
        dependencies: ["lucide-react"],
        files: ["text-02.tsx"],
    },
    {
        name: "text-03",
        type: "registry:component",
        dependencies: ["lucide-react"],
        files: ["text-03.tsx"],
    },
    {
        name: "text-04",
        type: "registry:component",
        dependencies: ["lucide-react"],
        files: ["text-04.tsx"],
    },
    {
        name: "text-05",
        type: "registry:component",
        dependencies: ["lucide-react"],
        files: ["text-05.tsx"],
    },
    {
        name: "text-06",
        type: "registry:component",
        dependencies: ["lucide-react"],
        files: ["text-06.tsx"],
    },
    {
        name: "card-01",
        type: "registry:component",
        dependencies: ["lucide-react", "framer-motion"],
        registryDependencies: ["select", "input", "button", "card", "label"],
        files: ["card-01.tsx"],
    },
    {
        name: "card-02",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["button", "card"],
        files: ["card-02.tsx"],
    },
    {
        name: "card-03",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["card"],
        files: ["card-03.tsx"],
    },
    {
        name: "card-04",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["button", "input"],
        files: ["card-04.tsx"],
    },
    {
        name: "card-05",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["button"],
        files: ["card-05.tsx"],
    },
    {
        name: "card-06",
        type: "registry:component",
        dependencies: ["lucide-react", "framer-motion"],
        registryDependencies: ["button", "card"],
        files: ["card-06.tsx"],
    },
    {
        name: "pricing-01",
        type: "registry:component",
        dependencies: ["lucide-react", "framer-motion"],
        registryDependencies: ["button"],
        files: ["pricing-01.tsx"],
    },
    {
        name: "pricing-02",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["button", "tooltip"],
        files: ["pricing-02.tsx"],
    },
    {
        name: "pricing-03",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["button"],
        files: ["pricing-03.tsx"],
    },
    {
        name: "pricing-04",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["button", "card"],
        files: ["pricing-04.tsx"],
    },
];
