import type { Registry } from "./schema";

export const ui: Registry = [
    {
        name: "ai-input-01",
        type: "registry:ui",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-01.tsx"],
    },
    {
        name: "ai-input-02",
        type: "registry:ui",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-02.tsx"],
    },
    {
        name: "ai-input-03",
        type: "registry:ui",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-03.tsx"],
    },
    {
        name: "ai-input-04",
        type: "registry:ui",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-04.tsx"],
    },
    {
        name: "ai-input-05",
        type: "registry:ui",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-05.tsx"],
    },
    {
        name: "ai-input-06",
        type: "registry:ui",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-06.tsx"],
    },
    {
        name: "ai-input-07",
        type: "registry:ui",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-07.tsx"],
    },
    {
        name: "ai-input-08",
        type: "registry:ui",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-08.tsx"],
    },
    {
        name: "ai-input-09",
        type: "registry:ui",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-09.tsx"],
    },
    {
        name: "ai-input-10",
        type: "registry:ui",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-10.tsx"],
    },
    {
        name: "ai-input-11",
        type: "registry:ui",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-11.tsx"],
    },
    {
        name: "ai-input-12",
        type: "registry:ui",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea", "tooltip"],
        files: ["ui/ai-input-12.tsx"],
    },
    {
        name: "ai-input-13",
        type: "registry:ui",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-13.tsx"],
    },
    {
        name: "ai-input-14",
        type: "registry:ui",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-14.tsx"],
    },
    {
        name: "ai-input-15",
        type: "registry:ui",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-15.tsx"],
    },
    {
        name: "ai-input-16",
        type: "registry:ui",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-16.tsx"],
    },
    {
        name: "ai-input-17",
        type: "registry:ui",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-17.tsx"],
    },
    {
        name: "ai-input-18",
        type: "registry:ui",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-18.tsx"],
    },
    {
        name: "ai-input-19",
        type: "registry:ui",
        dependencies: ["lucide-react", "framer-motion"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-19.tsx"],
    },
    {
        name: "ai-input-20",
        type: "registry:ui",
        dependencies: ["lucide-react", "framer-motion", "cmdk"],
        registryDependencies: ["textarea"],
        files: ["ui/ai-input-20.tsx"],
    },
];
