import type { Registry } from "./schema";

export const components: Registry = [
    {
        name: "ai-input-01",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-01.tsx"],
    },
    {
        name: "ai-input-02",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-02.tsx"],
    },
    {
        name: "ai-input-03",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-03.tsx"],
    },
    {
        name: "ai-input-04",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-04.tsx"],
    },
    {
        name: "ai-input-05",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-05.tsx"],
    },
    {
        name: "ai-input-06",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-06.tsx"],
    },
    {
        name: "ai-input-07",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-07.tsx"],
    },
    {
        name: "ai-input-08",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-08.tsx"],
    },
    {
        name: "ai-input-09",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-09.tsx"],
    },
    {
        name: "ai-input-10",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-10.tsx"],
    },
    {
        name: "ai-input-11",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-11.tsx"],
    },
    {
        name: "ai-input-12",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea", "tooltip"],
        files: ["components/ai-input-12.tsx"],
    },
    {
        name: "ai-input-13",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-13.tsx"],
    },
    {
        name: "ai-input-14",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-14.tsx"],
    },
    {
        name: "ai-input-15",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-15.tsx"],
    },
    {
        name: "ai-input-16",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-16.tsx"],
    },
    {
        name: "ai-input-17",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-17.tsx"],
    },
    {
        name: "ai-input-18",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-18.tsx"],
    },
    {
        name: "ai-input-19",
        type: "registry:component",
        dependencies: ["lucide-react", "framer-motion"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-19.tsx"],
    },
    {
        name: "ai-input-20",
        type: "registry:component",
        dependencies: ["lucide-react", "framer-motion", "cmdk"],
        registryDependencies: ["textarea"],
        files: ["components/ai-input-20.tsx"],
    },
    {
        name: "button-01",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["button"],
        files: ["components/btn-01.tsx"],
    },
    {
        name: "button-02",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["button"],
        files: ["components/btn-02.tsx"],
    },
    {
        name: "button-03",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["button"],
        files: ["components/btn-03.tsx"],
    },
    {
        name: "button-04",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["button"],
        files: ["components/btn-04.tsx"],
    },
    {
        name: "button-05",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["button"],
        files: ["components/btn-05.tsx"],
    },
    {
        name: "button-06",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["button"],
        files: ["components/btn-06.tsx"],
    },
    {
        name: "button-07",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["button"],
        files: ["components/btn-07.tsx"],
    },
    {
        name: "button-08",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["button"],
        files: ["components/btn-08.tsx"],
    },
    {
        name: "text-01",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["text"],
        files: ["components/text-01.tsx"],
    },
    {
        name: "text-02",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["text"],
        files: ["components/text-02.tsx"],
    },
    {
        name: "text-03",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["text"],
        files: ["components/text-03.tsx"],
    },
    {
        name: "text-04",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["text"],
        files: ["components/text-04.tsx"],
    },
    {
        name: "text-05",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["text"],
        files: ["components/text-05.tsx"],
    },
    {
        name: "text-06",
        type: "registry:component",
        dependencies: ["lucide-react"],
        registryDependencies: ["text"],
        files: ["components/text-06.tsx"],
    },
];
